CREATE TABLE usuario (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE cliente (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(255) NOT NULL,
    telefono  VARCHAR(255),
    email     VARCHAR(255),
    direccion VARCHAR(255)
);

CREATE TABLE vehiculo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa               VARCHAR(255) NOT NULL,
    marca               VARCHAR(255),
    modelo              VARCHAR(255),
    anio                INTEGER,
    kilometraje_actual  INTEGER,
    cliente_id          BIGINT NOT NULL,
    CONSTRAINT uk_vehiculo_placa UNIQUE (placa),
    CONSTRAINT fk_vehiculo_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE TABLE orden_de_trabajo (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_entrada          DATE NOT NULL,
    fecha_estimada_salida  DATE,
    fecha_real_salida      DATE,
    kilometraje_ingreso    INTEGER,
    problema_reportado     VARCHAR(255),
    diagnostico            VARCHAR(255),
    estado                 VARCHAR(255) NOT NULL,
    vehiculo_id            BIGINT NOT NULL,
    mecanico_asignado_id   BIGINT,
    CONSTRAINT fk_orden_vehiculo FOREIGN KEY (vehiculo_id) REFERENCES vehiculo (id),
    CONSTRAINT fk_orden_mecanico FOREIGN KEY (mecanico_asignado_id) REFERENCES usuario (id)
);
