CREATE TABLE producto (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(255) NOT NULL,
    nombre         VARCHAR(255) NOT NULL,
    categoria      VARCHAR(255),
    stock_actual   INTEGER NOT NULL,
    stock_minimo   INTEGER NOT NULL,
    precio_compra  NUMERIC(19, 2),
    precio_venta   NUMERIC(19, 2) NOT NULL,
    CONSTRAINT uk_producto_sku UNIQUE (sku)
);

CREATE TABLE item_orden (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo             VARCHAR(255) NOT NULL,
    producto_id      BIGINT,
    cantidad         INTEGER,
    precio_unitario  NUMERIC(19, 2),
    descripcion      VARCHAR(255),
    costo            NUMERIC(19, 2),
    orden_id         BIGINT NOT NULL,
    CONSTRAINT fk_item_orden_producto FOREIGN KEY (producto_id) REFERENCES producto (id),
    CONSTRAINT fk_item_orden_orden FOREIGN KEY (orden_id) REFERENCES orden_de_trabajo (id)
);

CREATE TABLE movimiento_inventario (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo                 VARCHAR(255) NOT NULL,
    cantidad             INTEGER NOT NULL,
    fecha                DATE NOT NULL,
    producto_id          BIGINT NOT NULL,
    referencia_orden_id  BIGINT,
    CONSTRAINT fk_movimiento_producto FOREIGN KEY (producto_id) REFERENCES producto (id),
    CONSTRAINT fk_movimiento_orden FOREIGN KEY (referencia_orden_id) REFERENCES orden_de_trabajo (id)
);
