CREATE TABLE factura (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero              VARCHAR(255) NOT NULL,
    fecha               DATE NOT NULL,
    orden_id            BIGINT NOT NULL,
    subtotal_repuestos  NUMERIC(19, 2) NOT NULL,
    subtotal_mano_obra  NUMERIC(19, 2) NOT NULL,
    total               NUMERIC(19, 2) NOT NULL,
    estado              VARCHAR(255) NOT NULL,
    CONSTRAINT uk_factura_numero UNIQUE (numero),
    CONSTRAINT uk_factura_orden UNIQUE (orden_id),
    CONSTRAINT fk_factura_orden FOREIGN KEY (orden_id) REFERENCES orden_de_trabajo (id)
);
