ALTER TABLE usuario ADD COLUMN email VARCHAR(255) NOT NULL;
ALTER TABLE usuario ADD COLUMN password_hash VARCHAR(255) NOT NULL;
ALTER TABLE usuario ADD COLUMN rol VARCHAR(50) NOT NULL;

ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);
